# Generated by Django 5.1.6 on 2025-03-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='musicfile',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the music file in the album'),
        ),
        migrations.AddField(
            model_name='musicfile',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='music_files', to='meditation.album'),
            preserve_default=False,
        ),
    ]
